project          = "teste-sample-388301"
region           = "us-central1"
credentials_file = "client-key.json"
db_name          = "petclinic"
db_user          = "petclinic"
db_pass          = "petclinic"
